### PR TITLE
Store withdraw request when confirmed

### PR DESCRIPTION
**Pull request by Bitcoinera**
Related to DistributedCollective/fastBTC-confirmation-node#35

Need to test it

### CODE REVIEW

**Comment by Bitcoinera** [comment]
I am not sure about this [one](https://github.com/DistributedCollective/FastBTC/pull/37/files#diff-46e9d8143133d156ecfcc963ca8ceeace296589bbe26e784500ce714e9c5a147R215).

I guess simply remove?

**Comment by Bitcoinera** [comment]
Working. Tested using the `storeWithdrawRequest.js` file in DistributedCollective/fastBTC-confirmation-node

**Comment by Bitcoinera** [comment]
:warning: Works together with https://github.com/DistributedCollective/fastBTC-confirmation-node/pull/35 :warning:

**Comment by jamiemadrox779** [comment]
Outdated

**Pull request closed without merging**
