### PR TITLE
separate deposit and transfer transactions tables

### LINKED ISSUE #28: Separate transfer (withdraw) and deposits tx
I am seeing that both the withdraw and deposit transactions are being stored in the same table, transactions.

This doesn't seem to be right, and rather leading to great confusion. It would be better to have these two separate, since right now the only thing to tell them apart is the txId being null or not. But doesn't seem like a good idea to keep them mixed in the same table

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #28 

Not sure 100% about the Foreign Key

### CODE REVIEW

**Comment by Bitcoinera** [comment]
ah yeah, makes more sense to tie it to the txId, no? Or the ID on the table :thinking: ?

**Comment by jamiemadrox779** [comment]
This can be only approved with successful test-cases

**Comment by Bitcoinera** [comment]
Need to get hang of that server

**Comment by ztane** [comment]
This actually needs database migrations

**Pull request closed without merging**
